server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wallet
    username: user
    password: pass
    hikari:
      minimum-idle: 4
      maximum-pool-size: 8

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:/changelog/changelog-master.yml

  rabbitmq:
    addresses: localhost:5672



